ARG FLAVOR=cpu
ARG BASE_IMAGE_FROM
FROM ${BASE_IMAGE_FROM} as road-core-rag-builder

ARG RHDH_DOCS_VERSIONS="1.6"
ARG OCP_DOCS_VERSION="4.19"
ARG NUM_WORKERS=1

USER 0
WORKDIR /rag-content

COPY ./examples/get_rhdh_plaintext_docs.sh ./
COPY ./examples/get_ocp_plaintext_docs.sh ./
COPY ./examples/asciidoctor_text ./asciidoctor_text

# Adjust path in script
RUN sed -i 's/examples\/asciidoctor_text/asciidoctor_text/' get_rhdh_plaintext_docs.sh

# Tell Python where to find the 'lightspeed_rag_content' module
ENV PYTHONPATH="/rag-content/src"

# Fetch all RHDH versions' docs + topic maps
RUN ./get_rhdh_plaintext_docs.sh ${RHDH_DOCS_VERSIONS}

# Fetch OCP docs + topic maps
RUN ./get_ocp_plaintext_docs.sh ${OCP_DOCS_VERSION}

# Generate a single set of embeddings for all RHDH versions
RUN python ./examples/generate_embeddings_rhdh.py \
        -f_rhdh rhdh-product-docs-plaintext \
        -f_ocp ocp-product-docs-plaintext/${OCP_VERSION} \
        -md embeddings_model \
        -mn ${EMBEDDING_MODEL} \
        -o vector_db/product_docs \
        -w ${NUM_WORKERS} \
        -i product-docs \
        -t rhdh-docs-topic-map \
        -v_ocp ${OCP_DOCS_VERSION}

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=road-core-rag-builder /rag-content/vector_db/product_docs /rag/vector_db/product_docs
COPY --from=road-core-rag-builder /rag-content/embeddings_model /rag/embeddings_model

RUN mkdir /licenses
COPY LICENSE /licenses/

LABEL com.redhat.component=rhdh-lightspeed-rag-content
LABEL description="Red Hat Developer Hub Lightspeed RAG content"
LABEL distribution-scope=private
LABEL io.k8s.description="Red Hat Developer Hub Lightspeed RAG content"
LABEL io.k8s.display-name="Red Hat Developer Hub Lightspeed RAG content"
LABEL io.openshift.tags="developerhub,rhdh,lightspeed,ai,assistant,rag"
LABEL name=rhdh-lightspeed-rag-content
LABEL release=0.0.1
LABEL url="https://github.com/road-core/rag-content"
LABEL vendor="Red Hat, Inc."
LABEL version=0.0.1
LABEL summary="Red Hat Developer Hub Lightspeed RAG content"

USER 65532:65532
